### ISSUE TITLE
Full demographic profile not shown for single geog

### ISSUE THREAD

**Issue by EricaMaurer** [NYCPlanning/labs-nyc-factfinder#361]
https://nyc-factfinder.planninglabs.nyc/profile/32/demographic

**Comment by andycochran** [comment]
I assume there's a problem with the SQL in `app/queries/profile-simple.js`.

**Comment by chriswhong** [comment]
Not seeing this anymore, I believe it was addressed in #394

**Comment by EricaMaurer** [comment]
i'm still seeing this problem (unless the update from #394 hasn't been pushed through yet)
